[project]
name = "homework1"
version = "0.1.0"
description = "HSE. Магистратура - 1 курс. Домашняя работа #1 по Язык Python для разработчиков"
readme = "README.md"
authors = [
    { name = "Evgeniy Gribanov", email = "evgeniy.therabbit@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
]

[dependency-groups]
dev = [
    "icecream>=2.2.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "--cov=homework1 --cov-branch --cov-report=term-missing"

[tool.coverage.report]
show_missing = true
